# Generated by Django 5.2.5 on 2025-08-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="bookshelf",
            new_name="Book",
        ),
    ]
